[package]
name = "plagr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
flate2 = "1.0.20"
clap = "2.33.3"
aes = "0.7.4"
block-modes = "0.8.1"
rand = "0.8.4"
rust-ini = "0.17.0"